quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/db_autoflex
quarkus.hibernate-orm.database.generation=drop-and-create
%dev.quarkus.datasource.username=autoflex
%dev.quarkus.datasource.password=autoflex
%dev.quarkus.hibernate-orm.log.sql=true
